# Generated by Django 6.0.2 on 2026-04-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customeraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentmethod',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit/Debit Card')], max_length=20),
        ),
    ]
